<#
.SYNOPSIS
Unpack a packed.json project archive into folders/files.

.DESCRIPTION
Reads the JSON transport envelope generated by pack.ps1/pack.py, decodes the
base64 JSON payload, creates directories, and writes the packed files to disk.

Supports both Python-style arguments:
  .\unpack.ps1 --input packed.json --target .

and PowerShell-style arguments:
  .\unpack.ps1 -Input packed.json -Target .
#>

$ErrorActionPreference = "Stop"
$DefaultInputName = "packed.json"

function Show-Usage {
    Write-Host "Usage: .\unpack.ps1 [--input <path>] [--target <path>]"
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  --input, -Input    Packed JSON file path. Default: packed.json."
    Write-Host "  --target, -Target  Destination directory to unpack into. Default: current directory."
    Write-Host "  --help, -Help, -h  Show this help."
}

function Parse-Arguments {
    param([string[]]$Arguments)

    $parsed = [ordered]@{
        Input = $DefaultInputName
        Target = "."
    }

    for ($i = 0; $i -lt $Arguments.Count; $i++) {
        $arg = $Arguments[$i]
        switch -Regex ($arg) {
            '^(--help|-Help|-h|/\?)$' {
                Show-Usage
                exit 0
            }
            '^(--input|-Input)$' {
                if ($i + 1 -ge $Arguments.Count) { throw "Missing value for $arg" }
                $i++
                $parsed.Input = $Arguments[$i]
                continue
            }
            '^(--target|-Target)$' {
                if ($i + 1 -ge $Arguments.Count) { throw "Missing value for $arg" }
                $i++
                $parsed.Target = $Arguments[$i]
                continue
            }
            default {
                throw "Unknown argument: $arg"
            }
        }
    }

    return $parsed
}

function Get-UnresolvedFileSystemPath {
    param([Parameter(Mandatory=$true)][string]$PathText)
    return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($PathText)
}

function New-Utf8NoBomEncoding {
    return New-Object System.Text.UTF8Encoding -ArgumentList $false
}

function Read-Utf8SigText {
    param([Parameter(Mandatory=$true)][string]$PathText)

    $bytes = [System.IO.File]::ReadAllBytes($PathText)
    $offset = 0
    if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
        $offset = 3
    }

    $utf8 = New-Utf8NoBomEncoding
    return $utf8.GetString($bytes, $offset, $bytes.Length - $offset)
}

function Escape-UnquotedControlsInJsonStrings {
    param([Parameter(Mandatory=$true)][string]$Text)

    $sb = New-Object System.Text.StringBuilder
    $inString = $false
    $escaped = $false

    foreach ($ch in $Text.ToCharArray()) {
        if ($inString) {
            if ($escaped) {
                [void]$sb.Append($ch)
                $escaped = $false
                continue
            }
            if ($ch -eq '\') {
                [void]$sb.Append($ch)
                $escaped = $true
                continue
            }
            if ($ch -eq '"') {
                [void]$sb.Append($ch)
                $inString = $false
                continue
            }
            if ($ch -eq "`n") {
                [void]$sb.Append('\n')
                continue
            }
            if ($ch -eq "`r") {
                [void]$sb.Append('\r')
                continue
            }
            if ($ch -eq "`t") {
                [void]$sb.Append('\t')
                continue
            }
            [void]$sb.Append($ch)
            continue
        }

        [void]$sb.Append($ch)
        if ($ch -eq '"') {
            $inString = $true
        }
    }

    return $sb.ToString()
}

function Escape-JsonStringValue {
    param([Parameter(Mandatory=$true)][string]$Value)

    return $Value.Replace('\', '\\').Replace('"', '\"').Replace("`n", '\n').Replace("`r", '\r').Replace("`t", '\t')
}

function Load-LegacyInnerPayload {
    param(
        [Parameter(Mandatory=$true)][string]$RawText,
        [Parameter(Mandatory=$true)][string]$Context,
        [Parameter(Mandatory=$true)][string]$OriginalError
    )

    $marker = '"content":"'
    if ($RawText.IndexOf($marker, [System.StringComparison]::Ordinal) -lt 0) {
        throw "Failed to decode JSON payload for $Context`: $OriginalError"
    }

    $sb = New-Object System.Text.StringBuilder
    $cursor = 0

    while ($true) {
        $start = $RawText.IndexOf($marker, $cursor, [System.StringComparison]::Ordinal)
        if ($start -lt 0) {
            [void]$sb.Append($RawText.Substring($cursor))
            break
        }

        $valueStart = $start + $marker.Length
        [void]$sb.Append($RawText.Substring($cursor, $valueStart - $cursor))

        $nextFile = $RawText.IndexOf('"},{"path":"', $valueStart, [System.StringComparison]::Ordinal)
        $nextEnd = $RawText.IndexOf('"}]}', $valueStart, [System.StringComparison]::Ordinal)

        $candidates = @()
        if ($nextFile -ge 0) { $candidates += $nextFile }
        if ($nextEnd -ge 0) { $candidates += $nextEnd }
        if ($candidates.Count -eq 0) {
            throw "Failed to decode JSON payload for $Context`: $OriginalError"
        }

        $valueEnd = ($candidates | Measure-Object -Minimum).Minimum
        $rawValue = $RawText.Substring($valueStart, $valueEnd - $valueStart)
        [void]$sb.Append((Escape-JsonStringValue $rawValue))
        $cursor = $valueEnd
    }

    $repaired = $sb.ToString()
    try {
        $payload = $repaired | ConvertFrom-Json
    }
    catch {
        throw "Failed to decode JSON payload for $Context`: $($_.Exception.Message)"
    }

    if ($null -eq $payload -or $payload.GetType().Name -notin @('PSCustomObject', 'OrderedHashtable', 'Hashtable')) {
        throw "Packed file must contain a JSON object: $Context"
    }

    return $payload
}

function Load-JsonResilient {
    param(
        [Parameter(Mandatory=$true)][string]$RawText,
        [Parameter(Mandatory=$true)][string]$Context
    )

    try {
        $payload = $RawText | ConvertFrom-Json
    }
    catch {
        $originalError = $_.Exception.Message
        $repaired = Escape-UnquotedControlsInJsonStrings $RawText
        try {
            $payload = $repaired | ConvertFrom-Json
        }
        catch {
            if ($Context -like '*payload_base64*') {
                $payload = Load-LegacyInnerPayload -RawText $RawText -Context $Context -OriginalError $originalError
            }
            else {
                throw "Failed to decode JSON payload for $Context`: $originalError"
            }
        }
    }

    if ($null -eq $payload -or $payload.GetType().Name -notin @('PSCustomObject', 'OrderedHashtable', 'Hashtable')) {
        throw "Packed file must contain a JSON object: $Context"
    }

    return $payload
}

function Get-JsonPropertyValue {
    param(
        [Parameter(Mandatory=$true)]$Object,
        [Parameter(Mandatory=$true)][string]$Name
    )

    if ($null -eq $Object) { return $null }

    if ($Object -is [System.Collections.IDictionary]) {
        if ($Object.Contains($Name)) { return $Object[$Name] }
        return $null
    }

    $prop = $Object.PSObject.Properties[$Name]
    if ($null -eq $prop) { return $null }
    return $prop.Value
}

function Read-Pack {
    param([Parameter(Mandatory=$true)][string]$PathText)

    $rawText = Read-Utf8SigText $PathText
    $payloadOuter = Load-JsonResilient -RawText $rawText -Context $PathText
    $encoding = [string](Get-JsonPropertyValue -Object $payloadOuter -Name "transport_encoding")
    $encoding = $encoding.Trim().ToLowerInvariant()

    if ($encoding -eq "base64-json") {
        $b64 = [string](Get-JsonPropertyValue -Object $payloadOuter -Name "payload_base64")
        if ([string]::IsNullOrWhiteSpace($b64)) {
            throw "Packed transport envelope is missing payload_base64."
        }

        try {
            $innerRaw = [System.Convert]::FromBase64String($b64)
        }
        catch {
            throw "Failed to decode payload_base64: $($_.Exception.Message)"
        }

        $utf8 = New-Utf8NoBomEncoding
        $innerText = $utf8.GetString($innerRaw)
        return Load-JsonResilient -RawText $innerText -Context "${PathText}::payload_base64"
    }

    # Backward-compatible fallback for older non-envelope packed files.
    return $payloadOuter
}

function Get-SafeRelativeParts {
    param([Parameter(Mandatory=$true)][string]$PathText)

    $text = ([string]$PathText).Trim()
    if ($text -eq "" -or $text -eq ".") {
        return @()
    }

    if ($text.StartsWith('/') -or $text.StartsWith('\')) {
        throw "Absolute paths are not allowed in pack: '$PathText'"
    }
    if ($text -match '^[A-Za-z]:') {
        throw "Absolute Windows drive paths are not allowed in pack: '$PathText'"
    }

    $normalized = $text.Replace('\', '/')
    $parts = @($normalized.Split([char]'/', [System.StringSplitOptions]::RemoveEmptyEntries))
    foreach ($part in $parts) {
        if ($part -eq "..") {
            throw "Parent path traversal is not allowed in pack: '$PathText'"
        }
    }

    return @($parts | Where-Object { $_ -ne "." })
}

function Join-RootWithParts {
    param(
        [Parameter(Mandatory=$true)][string]$RootPath,
        [Parameter(Mandatory=$true)][string[]]$Parts
    )

    $result = $RootPath
    foreach ($part in $Parts) {
        $result = [System.IO.Path]::Combine($result, $part)
    }
    return [System.IO.Path]::GetFullPath($result)
}

function Add-TrailingDirectorySeparator {
    param([Parameter(Mandatory=$true)][string]$PathText)
    if ($PathText.EndsWith([System.IO.Path]::DirectorySeparatorChar) -or $PathText.EndsWith([System.IO.Path]::AltDirectorySeparatorChar)) {
        return $PathText
    }
    return $PathText + [System.IO.Path]::DirectorySeparatorChar
}

function Get-PathComparison {
    if ($IsWindows -or $env:OS -eq "Windows_NT") {
        return [System.StringComparison]::OrdinalIgnoreCase
    }
    return [System.StringComparison]::Ordinal
}

function Assert-PathInsideRoot {
    param(
        [Parameter(Mandatory=$true)][string]$PathText,
        [Parameter(Mandatory=$true)][string]$RootPath
    )

    $pathFull = [System.IO.Path]::GetFullPath($PathText)
    $rootFull = [System.IO.Path]::GetFullPath($RootPath)
    $rootWithSeparator = Add-TrailingDirectorySeparator $rootFull
    $comparison = Get-PathComparison

    if ([string]::Equals($pathFull, $rootFull, $comparison)) { return }
    if (-not $pathFull.StartsWith($rootWithSeparator, $comparison)) {
        throw "Packed path escapes target root. Path: $pathFull Root: $rootFull"
    }
}

function Set-ModeBestEffort {
    param(
        [Parameter(Mandatory=$true)][string]$PathText,
        $ModeRaw
    )

    try {
        $mode = [int]$ModeRaw
    }
    catch {
        return
    }

    # Windows-compatible equivalent of Python os.chmod's practical behavior:
    # if owner write bit is absent, mark read-only; otherwise clear read-only.
    try {
        $attrs = [System.IO.File]::GetAttributes($PathText)
        if (($mode -band 128) -eq 0) {
            $attrs = $attrs -bor [System.IO.FileAttributes]::ReadOnly
        }
        else {
            $attrs = $attrs -band (-bnot [System.IO.FileAttributes]::ReadOnly)
        }
        [System.IO.File]::SetAttributes($PathText, $attrs)
    }
    catch {
        # Match the Python script's best-effort chmod behavior.
    }
}

$parsedArgs = Parse-Arguments -Arguments $args
$packedPath = [System.IO.Path]::GetFullPath((Get-UnresolvedFileSystemPath ([string]$parsedArgs.Input)))
$targetRoot = [System.IO.Path]::GetFullPath((Get-UnresolvedFileSystemPath ([string]$parsedArgs.Target)))

if (-not [System.IO.File]::Exists($packedPath)) {
    throw "Packed file not found: $packedPath"
}

[System.IO.Directory]::CreateDirectory($targetRoot) | Out-Null

$payload = Read-Pack -PathText $packedPath
$directories = Get-JsonPropertyValue -Object $payload -Name "directories"
$files = Get-JsonPropertyValue -Object $payload -Name "files"

if ($null -eq $directories -or $null -eq $files) {
    throw "Packed JSON is missing required 'directories'/'files' lists."
}
if (-not ($directories -is [System.Collections.IEnumerable]) -or $directories -is [string]) {
    throw "Packed JSON is missing required 'directories'/'files' lists."
}
if (-not ($files -is [System.Collections.IEnumerable]) -or $files -is [string]) {
    throw "Packed JSON is missing required 'directories'/'files' lists."
}

$createdDirs = 0
$writtenFiles = 0

foreach ($item in @($directories)) {
    $parts = @(Get-SafeRelativeParts ([string]$item))
    if ($parts.Count -eq 0) { continue }

    $outDir = Join-RootWithParts -RootPath $targetRoot -Parts $parts
    Assert-PathInsideRoot -PathText $outDir -RootPath $targetRoot
    [System.IO.Directory]::CreateDirectory($outDir) | Out-Null
    $createdDirs++
}

foreach ($record in @($files)) {
    if ($null -eq $record -or $record.GetType().Name -notin @('PSCustomObject', 'OrderedHashtable', 'Hashtable')) {
        continue
    }

    $pathValue = Get-JsonPropertyValue -Object $record -Name "path"
    $parts = @(Get-SafeRelativeParts ([string]$pathValue))
    if ($parts.Count -eq 0) { continue }

    $encoding = [string](Get-JsonPropertyValue -Object $record -Name "encoding")
    $encoding = $encoding.Trim().ToLowerInvariant()
    if ($encoding -ne "base64") {
        throw "Unsupported file encoding in pack: '$encoding'"
    }

    $contentB64 = [string](Get-JsonPropertyValue -Object $record -Name "content")
    try {
        $raw = [System.Convert]::FromBase64String($contentB64)
    }
    catch {
        # Some legacy packed payloads incorrectly store raw text here.
        $utf8 = New-Utf8NoBomEncoding
        $raw = $utf8.GetBytes($contentB64)
    }

    $outPath = Join-RootWithParts -RootPath $targetRoot -Parts $parts
    Assert-PathInsideRoot -PathText $outPath -RootPath $targetRoot

    $parent = [System.IO.Path]::GetDirectoryName($outPath)
    if ($parent) {
        [System.IO.Directory]::CreateDirectory($parent) | Out-Null
    }

    [System.IO.File]::WriteAllBytes($outPath, $raw)
    Set-ModeBestEffort -PathText $outPath -ModeRaw (Get-JsonPropertyValue -Object $record -Name "mode")
    $writtenFiles++
}

Write-Host "Unpacked from: $packedPath"
Write-Host "Target root: $targetRoot"
Write-Host "Directories created: $createdDirs"
Write-Host "Files written: $writtenFiles"
